export default {
    extends: 'lighthouse:default',
    settings: {
        output: 'html',
        locale:'zh',
        // formFactor: 'desktop', //'mobile'|'desktop'|'none';
        onlyCategories: [
            'performance',
            'best-practices',
            'pwa',
            'seo'
        ],
        onlyAudits: [
            'is-on-https',
            'service-worker',
            'viewport',
            'metrics/first-contentful-paint',
            'metrics/largest-contentful-paint',
            'metrics/first-meaningful-paint',
            'metrics/speed-index',
            'screenshot-thumbnails',
            'final-screenshot',
            'metrics/total-blocking-time',
            'metrics/max-potential-fid',
            'metrics/cumulative-layout-shift',
            'metrics/experimental-interaction-to-next-paint',
            'errors-in-console',
            'server-response-time',
            'metrics/interactive',
            'user-timings',
            'critical-request-chains',
            'redirects',
            'installable-manifest',
            'splash-screen',
            'themed-omnibox',
            'maskable-icon',
            'content-width',
            'image-aspect-ratio',
            'image-size-responsive',
            'preload-fonts',
            'deprecations',
            'mainthread-work-breakdown',
            'bootup-time',
            'uses-rel-preload',
            'uses-rel-preconnect',
            'font-display',
            'diagnostics',
            'network-requests',
            'network-rtt',
            'network-server-latency',
            'main-thread-tasks',
            'metrics',
            'performance-budget',
            'timing-budget',
            'resource-summary',
            'third-party-summary',
            'third-party-facades',
            'largest-contentful-paint-element',
            'lcp-lazy-loaded',
            'layout-shift-elements',
            'long-tasks',
            'no-unload-listeners',
            'non-composited-animations',
            'unsized-images',
            'valid-source-maps',
            'preload-lcp-image',
            'csp-xss',
            'full-page-screenshot',
            'script-treemap-data',
            'manual/pwa-cross-browser',
            'manual/pwa-page-transitions',
            'manual/pwa-each-page-has-url',
            'accessibility/accesskeys',
            'accessibility/aria-allowed-attr',
            'accessibility/aria-command-name',
            'accessibility/aria-hidden-body',
            'accessibility/aria-hidden-focus',
            'accessibility/aria-input-field-name',
            'accessibility/aria-meter-name',
            'accessibility/aria-progressbar-name',
            'accessibility/aria-required-attr',
            'accessibility/aria-required-children',
            'accessibility/aria-required-parent',
            'accessibility/aria-roles',
            'accessibility/aria-toggle-field-name',
            'accessibility/aria-tooltip-name',
            'accessibility/aria-treeitem-name',
            'accessibility/aria-valid-attr-value',
            'accessibility/aria-valid-attr',
            'accessibility/button-name',
            'accessibility/bypass',
            'accessibility/color-contrast',
            'accessibility/definition-list',
            'accessibility/dlitem',
            'accessibility/document-title',
            'accessibility/duplicate-id-active',
            'accessibility/duplicate-id-aria',
            'accessibility/form-field-multiple-labels',
            'accessibility/frame-title',
            'accessibility/heading-order',
            'accessibility/html-has-lang',
            'accessibility/html-lang-valid',
            'accessibility/image-alt',
            'accessibility/input-image-alt',
            'accessibility/label',
            'accessibility/link-name',
            'accessibility/list',
            'accessibility/listitem',
            'accessibility/meta-refresh',
            'accessibility/meta-viewport',
            'accessibility/object-alt',
            'accessibility/tabindex',
            'accessibility/td-headers-attr',
            'accessibility/th-has-data-cells',
            'accessibility/valid-lang',
            'accessibility/video-caption',
            'accessibility/manual/custom-controls-labels',
            'accessibility/manual/custom-controls-roles',
            'accessibility/manual/focus-traps',
            'accessibility/manual/focusable-controls',
            'accessibility/manual/interactive-element-affordance',
            'accessibility/manual/logical-tab-order',
            'accessibility/manual/managed-focus',
            'accessibility/manual/offscreen-content-hidden',
            'accessibility/manual/use-landmarks',
            'accessibility/manual/visual-order-follows-dom',
            'byte-efficiency/uses-long-cache-ttl',
            'byte-efficiency/total-byte-weight',
            'byte-efficiency/offscreen-images',
            'byte-efficiency/render-blocking-resources',
            'byte-efficiency/unminified-css',
            'byte-efficiency/unminified-javascript',
            'byte-efficiency/unused-css-rules',
            'byte-efficiency/unused-javascript',
            'byte-efficiency/modern-image-formats',
            'byte-efficiency/uses-optimized-images',
            'byte-efficiency/uses-text-compression',
            'byte-efficiency/uses-responsive-images',
            'byte-efficiency/efficient-animated-content',
            'byte-efficiency/duplicated-javascript',
            'byte-efficiency/legacy-javascript',
            'byte-efficiency/uses-responsive-images-snapshot',
            'dobetterweb/doctype',
            'dobetterweb/charset',
            'dobetterweb/dom-size',
            'dobetterweb/geolocation-on-start',
            'dobetterweb/inspector-issues',
            'dobetterweb/no-document-write',
            'dobetterweb/js-libraries',
            'dobetterweb/notification-on-start',
            'dobetterweb/password-inputs-can-be-pasted-into',
            'dobetterweb/uses-http2',
            'dobetterweb/uses-passive-event-listeners',
            'seo/meta-description',
            'seo/http-status-code',
            'seo/font-size',
            'seo/link-text',
            'seo/crawlable-anchors',
            'seo/is-crawlable',
            'seo/robots-txt',
            'seo/tap-targets',
            'seo/hreflang',
            'seo/plugins',
            'seo/canonical',
            'seo/manual/structured-data',
            'work-during-interaction',
        ],
        // skipAudits: [
        //
        // ]
        // maxWaitForFcp: '',
        // maxWaitForLoad: "",
        // blockedUrlPatterns: []
        /** Flag indicating the run should only audit. */
        // auditMode?: boolean | string;
        /** Flag indicating the run should only gather. */
        // gatherMode?: boolean | string;
        // throttlingMethod?: 'devtools'|'simulate'|'provided';
        // /** The throttling config settings. */
        // throttling?: ThrottlingSettings;
        /** If present, the run should only conduct this list of audits. */

    },
    // passes: [
    //     // {
    //     //     passName: 'fastPass',
    //     //     gatherers: ['fast-gatherer'],
    //     // },
    //     // {
    //     //     passName: 'slowPass',
    //     //     recordTrace: true,
    //     //     useThrottling: true,
    //     //     networkQuietThresholdMs: 5000,
    //     //     gatherers: ['slow-gatherer'],
    //     // }
    // ],
    // audits: [
    //     'first-contentful-paint',
    //     'byte-efficiency/uses-optimized-images',
    // ],
    categories: {
        performance: {
            title: 'Performance',
            description: 'This category judges your performance',
            auditRefs: [
                {id: 'first-meaningful-paint', weight: 2, group: 'metrics'},
                {id: 'first-contentful-paint', weight: 3, group: 'metrics'},
                {id: 'interactive', weight: 5, group: 'metrics'},
            ],
        }
    },
    groups: {
        'metrics': {
            title: 'Metrics',
            description: 'These metrics encapsulate your web app\'s performance across a number of dimensions.'
        },
    }
}
